[project]
name = "backend"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = [
    "alembic>=1.18.5",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "httpx>=0.28.1",
    "onnxruntime>=1.28.0",
    "paddleocr>=3.7.0",
    "paddlepaddle-gpu>=3.3.1",
    "paddlex[ocr]>=3.7.2",
    "pydantic-settings>=2.14.2",
    "python-multipart>=0.0.32",
    "sqlalchemy[asyncio]>=2.0",
]

[tool.uv]
environments = ["sys_platform == 'win32' and python_full_version >= '3.12'"]

[tool.uv.sources]
paddlepaddle-gpu = { url = "https://paddle-whl.bj.bcebos.com/stable/cu126/paddlepaddle-gpu/paddlepaddle_gpu-3.3.1-cp312-cp312-win_amd64.whl" }

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
