"""initial schema: organizations, clients, documents, workflows, requirements, junction

Revision ID: e44ef8cbb30b
Revises: 
Create Date: 2026-08-02 23:11:31.883337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e44ef8cbb30b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clients',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('on_track', 'awaiting_documents', 'review_required', 'action_required', 'completed', name='client_status'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_table('documents',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('source_filename', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('ocr_result_id', sa.String(length=64), nullable=True, comment='Maps to existing backend/data/results/{id}/'),
    sa.Column('document_type', sa.Enum('invoice', 'receipt', 'bank_statement', 'purchase_order', 'gst_return', 'unknown', name='document_type'), nullable=False),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'extracted', 'needs_review', 'validated', 'rejected', 'failed', name='document_status'), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Technical pipeline metadata: page_count, ocr_engine, model, timing'),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ocr_result_id')
    )
    op.create_index(op.f('ix_documents_client_id'), 'documents', ['client_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_table('workflows',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('workflow_type', sa.Enum('gst_filing', 'bookkeeping', 'tds_filing', 'audit', 'payroll', 'custom', name='workflow_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('collecting_documents', 'ready_for_review', 'in_review', 'ready_for_filing', 'completed', 'blocked', name='workflow_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_client_id'), 'workflows', ['client_id'], unique=False)
    op.create_index(op.f('ix_workflows_organization_id'), 'workflows', ['organization_id'], unique=False)
    op.create_table('workflow_document_requirements',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('invoice', 'receipt', 'bank_statement', 'purchase_order', 'gst_return', 'unknown', name='document_type'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False, comment="Human-readable label, e.g. 'Purchase Invoices'"),
    sa.Column('required_count', sa.Integer(), nullable=True, comment='How many are needed; NULL = open-ended (any number)'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_document_requirements_workflow_id'), 'workflow_document_requirements', ['workflow_id'], unique=False)
    op.create_table('workflow_documents',
    sa.Column('workflow_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['workflow_document_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'document_id', name='uq_workflow_document')
    )
    op.create_index(op.f('ix_workflow_documents_document_id'), 'workflow_documents', ['document_id'], unique=False)
    op.create_index(op.f('ix_workflow_documents_requirement_id'), 'workflow_documents', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_workflow_documents_workflow_id'), 'workflow_documents', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_documents_workflow_id'), table_name='workflow_documents')
    op.drop_index(op.f('ix_workflow_documents_requirement_id'), table_name='workflow_documents')
    op.drop_index(op.f('ix_workflow_documents_document_id'), table_name='workflow_documents')
    op.drop_table('workflow_documents')
    op.drop_index(op.f('ix_workflow_document_requirements_workflow_id'), table_name='workflow_document_requirements')
    op.drop_table('workflow_document_requirements')
    op.drop_index(op.f('ix_workflows_organization_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_client_id'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_client_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('organizations')
    # ### end Alembic commands ###
